import { JetBrains_Mono, Special_Elite } from "next/font/google";
import "@/style/globals.css";

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const specialElite = Special_Elite({
  variable: "--font-special-elite",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={`${jetBrainsMono.variable} ${specialElite.variable}`} lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
